version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: /tmp/scripts/stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /tmp/scripts/start_container.sh
      timeout: 300
      runas: root
